apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: sprowk/ambulance-ufe
  newName: sprowk/ambulance-ufe
  newTag: 2.0.2
- name: sprowk/ambulance-bb-webapi
  newName: sprowk/ambulance-bb-webapi
  newTag: 2.0.3
