apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv3am-ambulance-ufe-content
spec:
  microFrontend: cv3am-ambulance-ufe
  element: cv3am-blood-bank-app
  attributes:
    - name: base-path
      value: cv3am-blood-bank/
    - name: api-base
      value: /cv3am-api
    - name: blood-bank-id
      value: centralna-banka
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?cv3am-blood-bank(/.*)?$"
