apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv3am-ambulance-ufe-content
spec:
  microFrontend: cv3am-ambulance-ufe
  element: cv3am-ambulance-wl-app
  attributes:
    - name: base-path
      value: /cv3am-ambulance-wl/
    - name: api-base
      value: http://localhost:30081/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?cv3am-ambulance-wl(/.*)?$"
