apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv3am-ambulance-ufe-link
spec:
  microFrontend: polyfea-md-shell
  element: polyfea-md-app
  attributes:
    - name: headline
      value: Krvna banka cv3am
    - name: short-headline
      value: Krvna banka cv3am
    - name: supporting-text
      value: |
        System evidencie a spravy krvnych vakov
    - name: material-icon
      value: water_drop
    - name: href
      value: ./cv3am-blood-bank
  priority: 10
  displayRules:
    - anyOf:
      - context-name: applications
      - context-name: rail-content
      - context-name: drawer-content
