apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv1am-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /cv1am-openapi
            - name: BASE_URL
              value: /cv1am-openapi-ui